# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "Ubuntu130432"

  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-i386-vagrant-disk1.box"

  config.vm.network :forwarded_port, guest: 8090, host: 8090

  config.vm.network :private_network, ip: "192.168.254.11"

  # config.vm.synced_folder "src", "/hostsrc"
  config.vm.synced_folder "Files", "/hostfiles"

  config.vm.provision :chef_solo do |chef|
      chef.add_recipe "hipsnip-solr"

      chef.json = {  :java => {
                       :oracle          => { "accept_oracle_download_terms" => true },
                       :jdk_version     => "7"
                     },
                     :jetty => {
                        :port           => "8090",
                     },
                     :solr => {
                        :version        => "4.5.1",
                        :checksum       => "8726fa10c6b92aa1d2235768092ee2d4cd486eea1738695f91b33c3fd8bc4bd7",
                        :conf_src       => "/hostfiles/solr/",
                        :context_path   => "/",
                     }
                  }
  end

end